---
- name: Configure Ubuntu Laptop
  hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Install VSCode
      apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        state: present

    - name: Install VSCode extensions.
      ansible.builtin.command:
        cmd: code --install-extension {{ item }}
        creates: ~/.vscode/extensions/{{ item }}*
      become: no
      loop:
        - redhat.ansible
        - aaron-bond.better-comments
        - ms-python.python

    - name: Install Ansible pre-requisites.
      apt:
        name: software-properties-common
        state: present

    - name: Add Ansible repository.
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present
        update_cache: yes

    - name: Install Ansible.
      apt:
        name: ansible
        state: present

    - name: Install OpenSSH Server.
      apt:
        name: openssh-server
        state: present

    - name: Ensure sshd is started.
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Add VirtualBox secure key.
      ansible.builtin.apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add VirtualBox repository to apt.
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian focal contrib # Using focal since impish isn't present yet.
        state: present
        update_cache: yes

    - name: Install VirtualBox.
      apt:
        name: virtualbox-6.1
        state: present

    - name: Add Vagrant secure key.
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Vagrant repository to apt.
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com impish main
        state: present
        update_cache: yes

    - name: Install Vagrant.
      apt:
        name: vagrant
        state: present

    - name: Install VIM.
      apt:
        name: vim
        state: present
